// <auto-generated />
using CustomerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerAPI.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20241109165401_AddAddressToCustomer")]
    partial class AddAddressToCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("CustomerAPI.Models.Customer", b =>
                {
                    b.Property<int>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("customerAddr1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerAddr2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerTelephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerTown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("customerId");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
